all: problema2_2 problema2_4

problema2_2: problema2_2.cpp
	g++ -O2 problema2_2.cpp -o problema2_2

problema2_4: problema2_4.cpp
	g++ -O2 problema2_4.cpp -o problema2_4

clean:
	rm problema2_2 problema2_4
