all: problema3_1 problema3_2

problema3_1: problema3_1.cpp
	g++ -O2 problema3_1.cpp -o problema3_1

problema3_2: problema3_2.cpp
	g++ -O2 problema3_2.cpp -o problema3_2

clean:
	rm problema3_1 problema3_2
